# Generated by Django 6.0.7 on 2026-07-14 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('truck', models.CharField(blank=True, choices=[('Dry Van', 'Dry Van'), ('Flatbed', 'Flatbed'), ('Reefers', 'Reefers'), ('Box Truck', 'Box Truck'), ('Reefer Van', 'Reefer Van'), ('Power-Only', 'Power-Only'), ('Step Deck', 'Step Deck'), ('Conestoga', 'Conestoga'), ('Intermodal', 'Intermodal')], max_length=50, null=True)),
                ('message', models.TextField(max_length=5000)),
                ('sms_consent', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_submissions',
                'indexes': [models.Index(fields=['email'], name='idx_contact_email'), models.Index(fields=['created_at'], name='idx_contact_created_at')],
            },
        ),
    ]
